### ISSUE TITLE
关于BVID的储存

### ISSUE THREAD

**Issue by fcxuu** [Alexis-GP/recommendation_based_on_content#5]
有一个问题，就是视频的BVID，最终是储存在一个csv表格（类似于excel）里面还是一个类似于mysql的数据库里？
我写函数来读取的时候是读取出的BVID是直接全是各个不同视频的BVID还是说会先有一个up的UID作为索引，然后读取出不同的BVID？

**Comment by Alexis-GP** [comment]
先存csv或txt吧，具体格式我今天下午想想看
